#!/usr/bin/php
<?php
require_once("ladoc.php");
require_once('css.class.php');
require_once('image.class.php');
$arguments = array_shift($argv);
if (count($argv) < 2) {
    print "Veuillez respecter la structure voici la doc :" . PHP_EOL;
    print getDoc();
} else {
    $aguments  =  array_shift($argv);
    $isRecursive = false;
    $outputName = "sprite.png";
    $outputStyle = "style.css";
    foreach ($arguments as $key => $arg) {
        # code...
        switch ($arg) {
            case '-r' or '--recursive':
                $isRecursive = true;
                break;
            case '-i' or '--output-image':
                $outputName = $aguments[$key + 1];
                break;
            case '-s' or '--output-style':
                $outputStyle = $aguments[$key + 1];
                break;
            default:

                break;
        }
    }
}
