#!/usr/bin/php
<?php

if (count($argv)) {
    # code...
    print "Erreur";
} elseif (condition) {
    # code...
    $aguments  =  array_shift($argv);
}

if (condition) {
    # code...
}
foreach ($arguments as $key => $arg) {
    # code...
    switch ($arg) {
        case '-r':

            break;

        default:
            # code...
            break;
    }
}
